/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as GameRouteImport } from './routes/game'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GamePlayRouteImport } from './routes/game.play'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlayRoute = GamePlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => GameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/characters': typeof CharactersRoute
  '/game': typeof GameRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/game/play': typeof GamePlayRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/characters': typeof CharactersRoute
  '/game': typeof GameRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/game/play': typeof GamePlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRoute
  '/characters': typeof CharactersRoute
  '/game': typeof GameRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/game/play': typeof GamePlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/characters'
    | '/game'
    | '/reset-password'
    | '/game/play'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/characters' | '/game' | '/reset-password' | '/game/play'
  id:
    | '__root__'
    | '/auth'
    | '/characters'
    | '/game'
    | '/reset-password'
    | '/game/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  CharactersRoute: typeof CharactersRoute
  GameRoute: typeof GameRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/play': {
      id: '/game/play'
      path: '/play'
      fullPath: '/game/play'
      preLoaderRoute: typeof GamePlayRouteImport
      parentRoute: typeof GameRoute
    }
  }
}

interface GameRouteChildren {
  GamePlayRoute: typeof GamePlayRoute
}

const GameRouteChildren: GameRouteChildren = {
  GamePlayRoute: GamePlayRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  CharactersRoute: CharactersRoute,
  GameRoute: GameRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
