/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as GameRouteImport } from './routes/game'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdmRouteImport } from './routes/adm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamePlayRouteImport } from './routes/game.play'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicItchWebhookRouteImport } from './routes/api/public/itch-webhook'
import { Route as ApiPublicItchBuildRouteImport } from './routes/api/public/itch-build'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmRoute = AdmRouteImport.update({
  id: '/adm',
  path: '/adm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlayRoute = GamePlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => GameRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicItchWebhookRoute = ApiPublicItchWebhookRouteImport.update({
  id: '/api/public/itch-webhook',
  path: '/api/public/itch-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicItchBuildRoute = ApiPublicItchBuildRouteImport.update({
  id: '/api/public/itch-build',
  path: '/api/public/itch-build',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adm': typeof AdmRoute
  '/auth': typeof AuthRoute
  '/characters': typeof CharactersRoute
  '/game': typeof GameRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/game/play': typeof GamePlayRoute
  '/api/public/itch-build': typeof ApiPublicItchBuildRoute
  '/api/public/itch-webhook': typeof ApiPublicItchWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adm': typeof AdmRoute
  '/auth': typeof AuthRoute
  '/characters': typeof CharactersRoute
  '/game': typeof GameRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/game/play': typeof GamePlayRoute
  '/api/public/itch-build': typeof ApiPublicItchBuildRoute
  '/api/public/itch-webhook': typeof ApiPublicItchWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adm': typeof AdmRoute
  '/auth': typeof AuthRoute
  '/characters': typeof CharactersRoute
  '/game': typeof GameRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/game/play': typeof GamePlayRoute
  '/api/public/itch-build': typeof ApiPublicItchBuildRoute
  '/api/public/itch-webhook': typeof ApiPublicItchWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adm'
    | '/auth'
    | '/characters'
    | '/game'
    | '/reset-password'
    | '/game/play'
    | '/api/public/itch-build'
    | '/api/public/itch-webhook'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adm'
    | '/auth'
    | '/characters'
    | '/game'
    | '/reset-password'
    | '/game/play'
    | '/api/public/itch-build'
    | '/api/public/itch-webhook'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/adm'
    | '/auth'
    | '/characters'
    | '/game'
    | '/reset-password'
    | '/game/play'
    | '/api/public/itch-build'
    | '/api/public/itch-webhook'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmRoute: typeof AdmRoute
  AuthRoute: typeof AuthRoute
  CharactersRoute: typeof CharactersRoute
  GameRoute: typeof GameRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicItchBuildRoute: typeof ApiPublicItchBuildRoute
  ApiPublicItchWebhookRoute: typeof ApiPublicItchWebhookRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adm': {
      id: '/adm'
      path: '/adm'
      fullPath: '/adm'
      preLoaderRoute: typeof AdmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/play': {
      id: '/game/play'
      path: '/play'
      fullPath: '/game/play'
      preLoaderRoute: typeof GamePlayRouteImport
      parentRoute: typeof GameRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/itch-webhook': {
      id: '/api/public/itch-webhook'
      path: '/api/public/itch-webhook'
      fullPath: '/api/public/itch-webhook'
      preLoaderRoute: typeof ApiPublicItchWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/itch-build': {
      id: '/api/public/itch-build'
      path: '/api/public/itch-build'
      fullPath: '/api/public/itch-build'
      preLoaderRoute: typeof ApiPublicItchBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GameRouteChildren {
  GamePlayRoute: typeof GamePlayRoute
}

const GameRouteChildren: GameRouteChildren = {
  GamePlayRoute: GamePlayRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmRoute: AdmRoute,
  AuthRoute: AuthRoute,
  CharactersRoute: CharactersRoute,
  GameRoute: GameRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicItchBuildRoute: ApiPublicItchBuildRoute,
  ApiPublicItchWebhookRoute: ApiPublicItchWebhookRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
